### ISSUE TITLE
run_nl_all() fails and outputs non-intuitive error message if experiment(expname=x) is set incorrectly

### ISSUE THREAD

**Issue by ltdroy** [ropensci/nlrx#29]
## Issue

If the following code is run (R 3.5.3 x64, Windows, nlrx version 0.2.0), then the simulation fails with a difficult-to-interpret error message. 

## Code generating the issue

```

library(nlrx)

netlogopath <- file.path("C:/Program Files/NetLogo 6.1.0")
modelpath <- file.path(netlogopath, "app/models/Sample Models/Biology/Wolf Sheep Predation.nlogo")

nl <- nl(nlversion = "6.1.0",
         nlpath = netlogopath,
         modelpath = modelpath,
         jvmmem = 1024
         )

nl@experiment <- experiment(
  expname = "wolf sheep",
  outpath = outpath,
  repetition = 1,
  tickmetrics = "false",
  idsetup = "setup",
  idgo = "go",
  runtime=50,
#  evalticks=seq(40,50),
  metrics=c("count sheep", "count wolves", "count patches with [pcolor = green]"),
  metrics.turtles=list("turtles"= c("energy")),
  variables = list(
    "initial-number-sheep" = list(min=50, max=150, qfun="qunif"),
    "initial-number-wolves" = list(min=50, max=150, qfun="qunif")),
  constants = list(
    "model-version" = "\"sheep-wolves-grass\"",
    "grass-regrowth-time" = 30,
    "sheep-gain-from-food" = 4,
    "wolf-gain-from-food" = 20,
    "sheep-reproduce" = 4,
    "wolf-reproduce" = 5,
    "show-energy?" = "false"))

nl@simdesign <- simdesign_lhs(
  nl=nl,
  samples=3,
  nseed=1,
  precision=3
)

results <- run_nl_all(nl)

```

## Error message produced

> Error in util_gather_results(nl, outfile, seed, siminputrow) : 
>   Temporary output file C:\Users\LD\AppData\Local\Temp\RtmpOo3xQB\nlrx5572_14230106c1654.csvnot found. On unix systems this can happen if the default system temp folder is used.
>                 Try reassigning the default temp folder for this R session (unixtools package).

## Source of the problem

The apparent source of the problem appears to be that `expname="wolf sheep"`. If this is changed to `expname="wolf-sheep"` then the simulations runs without apparent errors. 

Have not tested against nlrx 0.3.0

**Comment by nldoc** [comment]
Thank you for your feedback and for already providing a solution.
I added an additional check for whitespaces in the expname string to the util_eval_experiment() function and a warning is now printed in such cases. Please note that this evaluation function is only executed when you attach a simdesign to your nl object and not when attaching the experiment itself.
nlrx 0.3.0 will contain this update and will be pushed to CRAN very soon.
Best, nldoc

**Comment by kiranaw** [comment]
Hi, 

I encountered the same error (temporary output file not found).
However, in my case, changing the expname didn't solve the problem.

**Comment by nldoc** [comment]
Hi @kiranaw,
on my PC the example above works. I also have Windows10 x64, R 3.6.1, NetLogo 6.1.0 and nlrx 0.3.0.
However, in the example above, the definition of the `outpath` variable in the experiment is missing, so be sure you have this variable or add an appropriate path directly in the experiment.

In general, this error message, "... *,csv not found", is sometimes hard to debug because it is always printed if something went wrong with the NetLogo model. It`s the first time R is taking action after a NetLogo simulation was started. For example, it can appear when the NetLogo model file was not found in the specified location. It can also appear when the model crashes during runtime. Or it can appear if the java virtual machine could not be started. Because it is not trivial to find out what is going on from R, it is somewhat difficult to code meaingful error messages for such errors. 

However, the model is a tested model from the models library and should not produce any runtime errors. Thus, I would assume that the batch call to NetLogo is not executed properly. Have you installed either oracle JDK 1.8 or openjdk 1.8 on your system and added java to the system PATH environmental variable? Could you please open a CMD and type `java -version` and report what is printed there?

Cheers,
nldoc

**Comment by nldoc** [comment]
Ok. That looks good. I still believe that the problem occurs because NetLogo can not be started correctly via commandline. Could you please verify that the `nlpath` and `modelpath` variables are defined correctly?
Furthermore, could you please verify that you are able to run NetLogo from the commandline manually? To check this, open a CMD, navigate to your NetLogo 6.1.0 folder. Then execute this command (make sure to change the --table path to a writable folder that exists on your system): `netlogo-headless.bat --model "app/models/IABM Textbook/chapter 4/Wolf Sheep Simple 5.nlogo" --experiment "Wolf Sheep Simple model analysis" --table "C:/out/test.csv"`
Cheers,
nldoc

**Comment by kiranaw** [comment]
Hi @nldoc ,

thank you very much! the problem is solved now. I figured out that my JAVA_HOME pointed to 
`C:\Program` `Files\Java\jdk1.8.0_221\bin` 
then I changed it to 
`C:\Program` `Files\Java\jdk1.8.0_221\`

and now the simulation works.

**Comment by nldoc** [comment]
Great to hear that the problem is now solved 👍
