### ISSUE TITLE
Running multiple simulations at once option (?)

### ISSUE THREAD

**Issue by cbutler112358** [ropensci/nlrx#34]
Hello,

I've searched online, including in the documentation, but I've yet to find an answer to my question. In NetLogo, when running an experiment, the user is prompted with the question of how many simulations NetLogo should run at once (I usually go with 4 for my laptop, for example). I'm not seeing this as an option for the nlrx package, and was curious as to whether or not it is possible, given that NetLogo clearly offers such functionality?

**Comment by nldoc** [comment]
Thank you very much for your question.
You are right, that NetLogo offers such functionality. However, we decided to not use the NetLogo parallelisation feauture, but manage all the parallelisation ourselves within R. We see this as an advantage, because it allows the user to define their own parallel execution loops, or even send jobs in parallel to remote computing clusters. So of course it is possible to run parallel simulations with nlrx.
For getting started, please read this part of the online documentation: [parallelisation](https://docs.ropensci.org/nlrx/articles/furthernotes.html#parallelisation-and-the-future-concept).
In general, you can utilize multiple cores when executing the `run_nl_all()` function in combination with a future plan from the future package (e.g. `plan(multisession)`). By default, it will distribute simulations with different random seeds to different cores. It is also possible to distribute chunks of the parameter matrix to different cores by using the split parameter.

If you have any more questions regarding this concept, feel free to reopen this issue.
Cheers
