### ISSUE TITLE
Experiment progression feedback

### ISSUE THREAD

**Issue by chain-ed-reaction** [ropensci/nlrx#42]
How would one implement a progress bar for the number of stimulations of total simulation completed in current experiment?
Perhaps a means to resume an experiment? I don't think it's impossible since nlrx would have that data already

**Comment by nldoc** [comment]
Dear @chain-ed-reaction,
thanks for your great feedback. Actually, I have thought about this too in the past. In general, it would be cool of course to have such a feature, but there are some pitfalls:

* progress bars are not trivial to implement for parallel execution (or will not work at all)
* progress bars will not be useful for most optimization or calibration approaches (because the number of total runs is not fixed beforehand)
* progress bars might give you information on "percentage of runs finished", but in many cases that does not mean anything. One run can take the same time as 1000 other runs, depends on the model and the parameterisation.

These are the main resaons why I decided to not implement a progress bar, but maybe it is time to reconsider this.
I agree, that in some cases it might be useful to know the number of runs that were calculated, and to know if the script is still working properly. I will look into this hopefully soon.

Specific to your case, do you have a fixed runtime in your model simulations? Or do you work with endless runtime and stop conditions? Have you ran a smaller benchmark to estimate the total time of your experiment? Depending on your simdesign, you might also see the total number of siumlations when you run `print(nl)`.

**Comment by chain-ed-reaction** [comment]
Thanks for the prompt reply @nldoc !!
In my model I have:
- Fixed runtime
- And a stop condition
- Was trying to run a smaller version of my model
    - Perhaps I should have limited to single parameter.
- Was using sobol simdesign
I will try out print(nl) had some trouble getting things working with R since I only have a frugal understanding of it.
And also for my particular model "percentage of runs finished" is something I would like to be aware of since I can come up with the higher estimate for remaining time since the runtime is fixed.

**Comment by nldoc** [comment]
Are you currently using any parallelisation approach for the sobol simulations (e.g. `future` package)?

Sobol simdesign can blow up quite fast if you want to study many parameters with a high number of samples. After attaching the simdesign, `print(nl)` should report you the estimated number of runs. If you know how long your model runs at average for one single simulation, (you can test that with `run_nl_one()` for example), cou can easily calculate how long this whole experiment will probably run.
You are right, as nearly all optimization algorithms, the genetic algorithm does not run in parallel unfortunately. The algorithm needs the final result of a simulation to generate the parameter set for the next one. This might only work with well optimized and fast running models.

Because it might take some time until I can work on the implementation, there is another approach you could use to get some response from your running simulations by writing output from NetLogo.
I would do it as follows:

1. add a input widget (type "string") on the interface of your netlogo model and give it a name, e.g. "nlrx_id"
2. in your R script add `idrunnum = nlrx_id` to the experiment definitions. This will transfer the current `siminputrow` and `random-seed` to the NetLogo model.
3. Create an output procedure to write a txt file in your NetLogo model, e.g.
```
    to log.finished
      file-open (word ".../" nlrx_id ".log")
      file-write nlrx_id
      file-close
    end
```
4. Add your output procedure as a final procedure to your experiment in the R script: `idfinal = log.finished`. This will execute the log procedure at the end of each simulation run.

Now you can observe the folder where you write the log files. Each finished simulation will create a text file. Instead of writing a log file for each simulation, you can also write into the same log file, but that may be less stable when executing in parallel.

Cheers,
nldoc

**Comment by chain-ed-reaction** [comment]
Wow that's a clever approach. I had used parallelisation, but the model parameters were quite a lot .
I had used this approach to write csv files in one experiment but left it since it seemed less efficient. I will surely try out the text file approach.
I am intending to run my experiments on an HPC as soon as I get the access. I have created a docker image to get all the software in a single download. Am attatching the link to my docker repo:
https://hub.docker.com/r/beva/r-nlogo it finally works in the sense I can run sample simulations with [Play with Docker](https://labs.play-with-docker.com/). I am yet to test it more regurously, since I have removed many build dependencies for R and nlrx to reduce image size.
I had read using docker in HPC is not a good idea due to permission issues, and was hoping to use [Singularity](https://sylabs.io/singularity/) in case it fails. 
Have you used any better workflow? I'm curious.

**Comment by nldoc** [comment]
Your docker approach sounds super interesting. I wanted to play around with docker since the beginning of the nlrx development but never had the time to explore it properly. So I will definetly look into your example and might come back to you with some questions ;)
It would actually be very cool to add a "How to use nlrx with docker" vignette to the package and documentation website.

I am working with a SLURM HPC cluster, so things might be different for you. I use the `clustermq` package to send my jobs to the HPC from a Rstudio-server running on another linux server. I do not use docker, I have just set up everything on the HPC manually (install java, R and R-packages, netlogo). Before I send my jobs to the HPC (via the Q function of the clustermq package, see example [here](https://docs.ropensci.org/nlrx/articles/furthernotes.html#using-the-clustermq-framework)), I upload all needed files (model, model inputs, etc.) to the HPC via the `ssh` package. Afterwards, the `ssh` package can also be used to download additional output from the HPC to my Rstudio-server session.

**Comment by chain-ed-reaction** [comment]
Docker might have not been a great way to go.
I got access to few systems at my institute, (HPC yet to obtain access). As expected docker is not available nor can be installed since only user permission.
- For installing singularity one of the [dependencies](https://sylabs.io/guides/3.0/user-guide/installation.html#install-dependencies) is not installed in the machine.
I thought since it seems to be not requiring root to install perhaps I could work with it.
For running natively also the machine does not have R.

> I have just set up everything on the HPC manually (install java, R and R-packages, netlogo).

Did you have root access or did you compile the software for single user?
I have a feeling that I may have to stick with native software if I am to use the HPC of my institute.
If that doesn't workout well, I am considering buying a cloud instance where docker would run without any problem. 
I did like the clustermq documentation since it seemed to have less dependencies, than future. Did not go through all the documentation since for my local machine future was easier to use.
Perhaps I'll add a version of docker image having clustermq instead of future and it's dependencies.

**Comment by nldoc** [comment]
Yes, you may need to contact the administrators of your HPC to get some things installed for you.
In my case, our HPC allows to load certain software via "modules" on startup of any ssh connection (via .bashrc, [here](https://r-spatialecology.github.io/gwdg_hpc_guide/) is an example of our HPC setup workflow). 
On our HPC, there were already modules available for R, java and a gcc complier which I could load. R packages were installed in the user library, so no root was needed. NetLogo can also be downloaded and unzipped without root access (I used the `download_netlogo()` function of the nlrx package). I think some linux system dependencies were mising at some point, but I just sent a mail to our HPC administrators and they were happy to install some stuff for me.

I can defenitely recommend the clustermq package for sending jobs to the HPC. Works way more stable than the future package, which I only use for local parallelization. However, recently they even added an option to use clustermq for parallelization on your local machine which I did not try yet. You only need to change the clustermq.scheduler option:
`options(clustermq.scheduler="multiprocess")`

Regarding your docker approach, currently I am quite busy with other research stuff, but I will probably come back to you when I have more time to work on improving nlrx and its documentation again 👍

**Comment by chain-ed-reaction** [comment]
Sure👍🏾. Will try contacting the administrators. 
Good luck on your research.

**Comment by nldoc** [comment]
I finally had some time to check out progress bar options for nlrx.
I decided to go along with the [progressr](https://github.com/HenrikBengtsson/progressr) framework.
By default, the `run_nl_all()` function will be silent. But you can wrap it within `progressr::with_progress(run_nl_all())` and it will display a progress bar. You can also use different handlers which will affect the asethetics of the progress bar. It also works for parallel future plans (multisession). While I worked on the code I also decided to get rid of the "silent" parameter of the `run_nl_*` functions because they were not really helpful anymore.
I am still experimenting with some features but it should work now in the development version (`remotes::install_github("ropensci/nlrx")`).
