### ISSUE TITLE
Missing blank spaces in turtles-own lists

### ISSUE THREAD

**Issue by ghost** [ropensci/nlrx#49]
Hi! 

I'm currently facing problems with list outputs (I know that there is another issue on lists but I think my question is different). The NLRX output of lists that are defined as globals works fine but when I have a list as turtles-own or patches-own, blank spaces are missing in the NLRX output of that list in metrics.turtles, i.e. one gets an output of "[74148222]" instead of "[74 148 222]".

The behavior can be reproduced by adding, for example, an energy-list to the turtles-own in the Wolf Sheep Predation, i.e. by adding

```
turtles-own [ energy energy-list ]
```

and

```
ask turtles [ set energy-list (list energy (energy * 2) (energy * 3)) ]
```

in the go procedure and 

````R
metrics.turtles = list("turtles" = c("energy-list"))
````

in the example of simdesign_simple that you provide.

I also tried a workaround and implemented a function that converts the list to a quasi-R vector in NetLogo (a string in the form "c(..., ..., ...)") which can be converted to a real vector in R. However, this also only works for global variables but truncates the string after the first comma (i.e. the output is "c(...")) for turtles-own and patches-own lists (and gives the warning Expected 3 pieces. Additional pieces discarded...).

Thanks for your help (and for this great package which in general works perfect)!

**Comment by nldoc** [comment]
Hi,

the issue was kind-of fixed with #82.

I have added basic support for list output in agent-owns variables (turtles, patches, links) by slightly changing the way how we parse the NetLogo output.

It should now work to measure list variables of agents without losing whitespaces.
However, I did not add automatic parsing of these list structures into R (i.e., they will be reported as character strings). The problem here is, that parsing Netlogo list output in a general way is a quite complex endeavour, because lists might include complex nesting. See also #41 on this topic.

In the current version, the List variables will just be reported as string, for example "[1 12 15]", or "[1 12 [3 5]]" in case of nested lists. It is then up to the user to parse these agent metrics into usable formats in the post-processing.

Still, an automatic parser which can handle complex nested list output is still on the ToDo-list ;).

Feel free to re-test your example and re-open if it does not work as expected.
