### ISSUE TITLE
NLRX package archived on CRAN

### ISSUE THREAD

**Issue by Thomas-Bayley** [ropensci/nlrx#53]
The NLRX package has been archived on CRAN with the following message:

"_Package ‘nlrx’ was removed from the CRAN repository.

Formerly available versions can be obtained from the archive.

Archived on 2021-06-03 as email to the maintainer was undeliverable.

A summary of the most recent check results can be obtained from the check results archive.

Please use the canonical form https://CRAN.R-project.org/package=nlrx to link to this page._"

As a result it's not possible anymore to install the package in the normal way via the R-console, and instead has to be done from the archive, which has been quite tricky to get sorted and has left me less confident that everything has been installed properly.

**Comment by nldoc** [comment]
Dear Thomas,
thank you very much for letting me know of that issue.
I am not sure why this happened, but probably I did miss to update my email address properly in the description.
I am still wondering, because I did receive an email from Mister Ripley on June 3rd, and the former nlrx CRAN page mentions exactly this date. I will try to take care of that issue as soon as possible.
Until nlrx is up on CRAN again you can safely install nlrx from github using the remotes package:
```
install.packages("remotes")
remotes::install_github("ropensci/nlrx")
```
This is probably easier than installing from the CRAN archive.
Cheers,
Jan

**Comment by Thomas-Bayley** [comment]
Okay great, thanks for your help.

Best wishes,

Thomas

**Comment by bitbacchus** [comment]
We're back on CRAN :tada:
